DjangoEcommerce/DjangoEcommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from DjangoEcommerceApp import views
from django.conf import settings
# from DjangoEcommerceApp import AdminViews
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', views.adminLogin,name="admin_login"),
    path('',include("DjangoEcommerceApp.urls")), 
    path('',include("DjangoEcommerceApp.adminurls"))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

DjangoEcommerce/DjangoEcommerceApp/urls.py
from django.urls import path
from . import views
from . import AdminViews
from . import customerViews, MerchantViews

urlpatterns = [
    
    path('auth', views.index, name= 'index'),
    path("product/<int:product_id>/", customerViews.ProductDetailView.as_view(), name="product_detail"),
    path('b', customerViews.CombinedListView.as_view(), name="combined_list"),
    path('', views.combined_auth_view, name="combined_auth"),
    path('login/', views.login_view, name='login_view'),
    path('logout_process',views.LogoutProcess,name="logout_process"),
    path('register/', views.register, name='register'),
    path('merchant/', views.merchant, name='merchant'),
    path('contact.html/', views.contact_view, name='contact'),
    path('about.html/', views.about, name='about'),
    path('login/contact.html/', views.contact_view, name='contact_html'),
    path('login/about.html/', views.about, name='about'),
    path('login/wishlist.html/', views.wishlist, name='wishlist'),
    path('login/category.html', views.category_list, name='category_view'),

    path('category.html/', views.category_list, name='category_list'),
    path('blog.html/', views.blog, name='blog'),
    path('shop.html', views.shop, name = 'shop'),
    path('faq.html', views.faq, name='faq'),
    path('wishlist.html', views.wishlist, name='wishlist'),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    path('biss',views.index1, name = "home2"),
    path('cart', MerchantViews.cart, name = 'cart'),
    path('checkout.html/', views.checkout, name='checkout'),
    path('about.html/blog.html', views.blog, name='about.html/blog.html'),

    # ... other url patterns
    path('add/', views.add_service, name='add_service'),
    path('edit/<int:pk>/', views.edit_service, name='edit_service'),
    path('delete/<int:pk>/', views.delete_service, name='delete_service'),
    path('serve', views.service_list, name='service_list'),
    path('<int:pk>/', views.service_detail, name='service_detail'),
    path('book/<int:service_id>/', views.create_booking, name='create_booking'),
    path('booked-services/', views.booked_services_list, name='booked_services_list'),

]

DjangoEcommerce/DjangoEcommerceApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse

   
class CustomUser(AbstractUser):
    user_type_choices = ((1, "Admin"), (2, "Merchant"), (3, "Customer"))
    user_type = models.IntegerField(choices=user_type_choices, default=1)

    def save(self, *args, **kwargs):
        is_new = self._state.adding
        super().save(*args, **kwargs)
        if is_new and self.user_type == 3:  # Check if it's a new customer user
            CustomerUser.objects.create(auth_user_id=self)  # Create a CustomerUser instance

@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created and instance.user_type == 3:
        CustomerUser.objects.create(auth_user_id=instance)

post_save.connect(create_user_profile, sender=CustomUser)

class AdminUser(models.Model):
    profile_pic=models.FileField(default="")
    auth_user_id=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)


class MerchantUser(models.Model):
    auth_user_id=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    profile_pic=models.FileField(default="")
    company_name=models.CharField(max_length=255)
    gst_details=models.CharField(max_length=255)
    address=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()


class CustomerUser(models.Model):
    auth_user_id=models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    profile_pic=models.FileField(default="")
    created_at=models.DateTimeField(auto_now_add=True)


class Categories(models.Model):
    id=models.AutoField(primary_key=True)
    title=models.CharField(max_length=255)
    url_slug=models.CharField(max_length=255)
    thumbnail=models.FileField()
    description=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    is_active=models.IntegerField(default=1)

    def get_absolute_url(self):
        return reverse("category_list")

    def __str__(self):
        return self.title
    
    


class SubCategories(models.Model):
    id=models.AutoField(primary_key=True)
    category_id=models.ForeignKey(Categories,on_delete=models.CASCADE)
    title=models.CharField(max_length=255)
    url_slug=models.CharField(max_length=255)
    thumbnail=models.FileField()
    description=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    is_active=models.IntegerField(default=1)

    def get_absolute_url(self):
        return reverse("sub_category_list")
    


class Products(models.Model):
    id=models.AutoField(primary_key=True)
    url_slug=models.CharField(max_length=255)
    subcategories_id=models.ForeignKey(SubCategories,on_delete=models.CASCADE)
    product_name=models.CharField(max_length=255)
    brand=models.CharField(max_length=255)
    product_max_price=models.PositiveIntegerField(default=1)
    product_discount_price=models.PositiveIntegerField(default=1)
    product_description=models.TextField()
    product_long_description=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    added_by_merchant=models.ForeignKey(MerchantUser,on_delete=models.CASCADE)
    in_stock_total=models.IntegerField(default=1)
    is_active=models.IntegerField(default=1)

class ProductMedia(models.Model):
    id=models.AutoField(primary_key=True)
    product_id=models.ForeignKey(Products,on_delete=models.CASCADE)
    media_type_choice=((1,"Image"),(2,"Video"))
    media_type=models.CharField(max_length=255)
    media_content=models.FileField()
    created_at=models.DateTimeField(auto_now_add=True)
    is_active=models.IntegerField(default=1)  

class ProductTransaction(models.Model):
    id=models.AutoField(primary_key=True)
    transaction_type_choices=((1,"BUY"),(2,"SELL"))
    product_id=models.ForeignKey(Products,on_delete=models.CASCADE)
    transaction_product_count=models.IntegerField(default=1)
    transaction_type=models.CharField(choices=transaction_type_choices,max_length=255)
    transaction_description=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)


class ProductDetails(models.Model):
    id=models.AutoField(primary_key=True)
    product_id=models.ForeignKey(Products,on_delete=models.CASCADE)
    title=models.CharField(max_length=255)
    title_details=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    is_active=models.IntegerField(default=1)

class ProductAbout(models.Model):
    id=models.AutoField(primary_key=True)
    product_id=models.ForeignKey(Products,on_delete=models.CASCADE)
    title=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    is_active=models.IntegerField(default=1)

class ProductTags(models.Model):
    id=models.AutoField(primary_key=True)
    product_id=models.ForeignKey(Products,on_delete=models.CASCADE)
    title=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    is_active=models.IntegerField(default=1)


class ProductReviews(models.Model):
    id=models.AutoField(primary_key=True)
    product_id=models.ForeignKey(Products,on_delete=models.CASCADE)
    user_id=models.ForeignKey(CustomerUser,on_delete=models.CASCADE)
    review_image=models.FileField()
    rating=models.CharField(default="5",max_length=255)
    review=models.TextField(default="")
    created_at=models.DateTimeField(auto_now_add=True)
    is_active=models.IntegerField(default=1)


class ProductVarient(models.Model):
    id=models.AutoField(primary_key=True)
    title=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)

class ProductVarientItems(models.Model):
    id=models.AutoField(primary_key=True)
    product_varient_id=models.ForeignKey(ProductVarient,on_delete=models.CASCADE)
    product_id=models.ForeignKey(Products,on_delete=models.CASCADE)
    title=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)

class CustomerOrders(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Products, on_delete=models.DO_NOTHING)
    user_id = models.ForeignKey(CustomerUser, on_delete=models.CASCADE, default=3)
    product_max_price=models.PositiveIntegerField(default=1)
    coupon_code = models.CharField(max_length=255)
    discount_amt = models.PositiveIntegerField(default=1)
    product_status = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField(default=1)  # New field for quantity
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order ID: {self.id}, Product: {self.product_id}"


class OrderDeliveryStatus(models.Model):
    id=models.AutoField(primary_key=True)
    order_id=models.ForeignKey(CustomerOrders,on_delete=models.CASCADE)
    status=models.CharField(max_length=255)
    status_message=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)

class Service(models.Model):
    id = models.AutoField(primary_key=True)
    service_name = models.CharField(max_length=255)
    description = models.TextField()
    duration = models.DurationField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available_slots = models.IntegerField(default=1)
    scheduled_at = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    available_slots = models.IntegerField(default=1) 
    booked_slots = models.IntegerField(default=0) 

    @property
    def remaining_slots(self):
        return self.available_slots - self.booked_slots

class ServiceMedia(models.Model):
    id = models.AutoField(primary_key=True)
    service_id = models.ForeignKey(Service, on_delete=models.CASCADE)
    media_type_choice = ((1, "Image"), (2, "Video"))
    media_type = models.CharField(max_length=255)
    media_content = models.FileField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.IntegerField(default=1)

class Booking(models.Model):
    id = models.AutoField(primary_key=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    booking_date = models.DateTimeField()
    additional_details = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

DjangoEcommerce/DjangoEcommerceApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from .models import CustomUser, AdminUser, MerchantUser, CustomerUser
from .models import Service, ServiceMedia, Booking
from django.core.files.storage import FileSystemStorage


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['service_name', 'description', 'duration', 'price', 'available_slots', 'scheduled_at']

class ServiceMediaForm(forms.ModelForm):
    media_content = forms.ImageField(label='Select a file', help_text='max. 42 megabytes')

    class Meta:
        model = ServiceMedia
        fields = ['media_content']  # Removed 'media_type' from the fields

    def save(self, commit=True):
        instance = super(ServiceMediaForm, self).save(commit=False)
        instance.media_type = 'image'  # Set 'media_type' to 'image' automatically
        if commit:
            instance.save()
        return instance
class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['service', 'booking_date', 'additional_details']



class LoginForm(forms.Form):
    username = forms.CharField(
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )

class SignUpForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}))
    email = forms.EmailField(widget=forms.TextInput(attrs={"class": "form-control"}))
    user_type = forms.ChoiceField(
        choices=[(2, "Merchant"), (3, "Customer")],  # Exclude the Admin choice
        widget=forms.RadioSelect(),
        initial=3  # Set Customer as the default selection
    )
    profile_pic = forms.ImageField(
        required=False,  # Make it optional
        widget=forms.FileInput(attrs={"class": "form-control"})
    )
    company_name = forms.CharField(
        required=False,  # Only required for merchants
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    gst_details = forms.CharField(
        required=False,  # Only required for merchants
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    address = forms.CharField(
        required=False,  # Only required for merchants
        widget=forms.Textarea(attrs={"class": "form-control", "rows": 3})
    )

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2', 'user_type', 'profile_pic','company_name', 'gst_details', 'address')

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.user_type = self.cleaned_data.get('user_type')
        user.save()
        

        profile_pic = None
        if 'profile_pic' in self.files:
            profile_pic_file = self.files['profile_pic']
            fs = FileSystemStorage()
            filename = fs.save(profile_pic_file.name, profile_pic_file)
            profile_pic = filename

        if user.user_type == '2':
            MerchantUser.objects.create(
                auth_user_id=user,
                profile_pic=profile_pic,  # Assign the file name
                company_name=self.cleaned_data.get('company_name'),
                gst_details=self.cleaned_data.get('gst_details'),
                address=self.cleaned_data.get('address')
            )
        elif user.user_type == '3': 
            CustomerUser.objects.create(
                auth_user_id=user,
                profile_pic=profile_pic  # Assign the file name
            )
        return user

DjangoEcommerce/DjangoEcommerceApp/templates/customer/blog.html
{% extends 'customer/base.html' %}
{% load static %}
{% block custom_css %}
<!-- <style>

    body, h1, h2, h3, p, blockquote, ul, li {
        margin: 0;
        padding: 0;
    }

    
    body {
        font-family: poppins, sans-serif;
        line-height: 1.6;
        background-image: url(images/aboutnew.jpg); 
        background-size: cover; 
        background-position: center;
        color: #333;
        margin: 0;
        padding: 0;
    }

    .highlight {
        color: blue; 
        text-decoration: underline;
        cursor: pointer
    }

    .highlight:hover {
        font-weight: bold; 
    }

    .highlight:active {
        font-weight: bold;
    }


   

    #header {
        background-color: #fcecca;
        padding: 20px 80px;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.06);
        z-index: 999;
        position: sticky;
        top: 0;
        left: 0;
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    header h1 {
        font-size: 36px;
        margin-bottom: 10px;
    }
    article {
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

   
    section {
        margin-bottom: 20px;
    }

    section h2 {
        font-size: 24px;
        margin-bottom: 10px;
    }

    section p {
        margin-bottom: 15px;
    }

    
    blockquote {
        background-color: #fdcfae;
        border-left: 5px solid #ddd;
        padding: 10px 20px;
        margin: 15px 0;
    }

  
    footer {
        margin-top: 80px;
        text-align: center;
    }

    footer p {
        font-size: 14px;
    }
</style> -->
{% endblock custom_css %}

{% block page_content %}
<title>Blog</title>
<body>
    <div class="page-header text-center" style="background-image: url({% static 'assets/img/news/img13.jpg' %});">

        <div class="container">
            <h1 class="page-title">Learn More About Us</h1>
        </div><!-- End .container -->
    </div><!-- End .page-header -->
    <!-- <section id="header">
        <a href="index.html" class="logo">
            <img src="{% static 'assets/images/logo.png' %}"  alt="Logo" width="105" height="60">
        </a>
    

        <div>
            <ul id="navbar">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a class="active" href="{% url 'blog' %}">Blog</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
                <li><a href="{% url 'cart' %}"><i class="far fa-shopping-cart"></i></a></li>
            </ul>

        </div>
    </section>
    <article>

           </div>
   </section> -->

   <article>

        <!-- <section id="introduction">
            <h2>Learn More About Us</h2>
            
        </section> -->

        <section id="body">
            <h2>Main Content</h2>
            <p>Your ultimate destination for fantastic deals on various products</p>
            <p>Discover a world of sustainable living with our eco-friendly collection, including fashion,home goods, and lifestyle essentials. 
                Embrace ethical production and durable designs in clothing while also exploring toxin-free options for home decor,wellness products and more.</p>
                <p>Shop with purpose , Shop sustainability and style that reflect your values. </p>

            <blockquote>
                <p>Find durable and stylish pieces that prioritize your health and make a positive difference <a href="index.html" class="highlight">Here</a>.</p>
            </blockquote>

            
        </section>
        <div class="blog-posts pt-7 pb-7" style="background-color: #fafafa;">
            <div class="container">
               <h2 class="title-lg text-center mb-3 mb-md-4">Latest Articles</h2><!-- End .title-lg text-center -->
    
                <div class="owl-carousel owl-simple carousel-with-shadow" data-toggle="owl" 
                    data-owl-options='{
                        "nav": false, 
                        "dots": true,
                        "items": 3,
                        "margin": 20,
                        "loop": false,
                        "responsive": {
                            "0": {
                                "items":1
                            },
                            "600": {
                                "items":2
                            },
                            "992": {
                                "items":3
                            }
                        }
                    }'>
                    <article class="entry entry-display">
                        <figure class="entry-media">
                            <a href="single.html">
                                <img src="{% static 'assets\images\blog\comments\new2.jpg' %}" alt="image desc">
                            </a>
                        </figure><!-- End .entry-media -->
    
                        <div class="entry-body pb-4 text-center">
                            <div class="entry-meta">
                                <a href="#">Feb 22, 2024</a>, 0 Comments
                            </div><!-- End .entry-meta -->
    
                            <h3 class="entry-title">
                                <a href="single.html">Utilize Social Media and Digital Marketing.</a>
                            </h3><!-- End .entry-title -->
    
                            <div class="entry-content">
                                <p>Create engaging content, run targeted ads, and utilize influencer partnerships to expand your reach and drive sales.<br>Create a Consistent Brand . </p>
                                <a href="single.html" class="read-more">Read More</a>
                            </div><!-- End .entry-content -->
                        </div><!-- End .entry-body -->
                    </article><!-- End .entry -->
    
                    <article class="entry entry-display">
                        <figure class="entry-media">
                            <a href="single.html">
                                <img src="{% static 'assets\images\blog\comments\new..jpg' %}" alt="image desc">
                            </a>
                        </figure><!-- End .entry-media -->
    
                        <div class="entry-body pb-4 text-center">
                            <div class="entry-meta">
                                <a href="#">Jan 20 2024</a>, 0 Comments
                            </div><!-- End .entry-meta -->
    
                            <h3 class="entry-title">
                                <a href="single.html">Stay Updated with E-Commerce Trends.</a>
                            </h3><!-- End .entry-title -->
    
                            <div class="entry-content">
                                <p>Keep abreast of the latest e-commerce trends, technologies, and consumer preferences.</p>
                                <a href="single.html" class="read-more">Read More</a>
                            </div><!-- End .entry-content -->
                        </div><!-- End .entry-body -->
                    </article><!-- End .entry -->
    
                    <article class="entry entry-display">
                        <figure class="entry-media">
                            <a href="single.html">
                                <img src="{% static 'assets\images\blog\comments\new3.jpg' %}" alt="image desc">
                            </a>
                        </figure><!-- End .entry-media -->
    
                        <div class="entry-body pb-4 text-center">
                            <div class="entry-meta">
                                <a href="#">Jan 17 2024</a>, 2 Comments
                            </div><!-- End .entry-meta -->
    
                            <h3 class="entry-title">
                                <a href="single.html">Engage with Your Audience.</a>
                            </h3><!-- End .entry-title -->
    
                            <div class="entry-content">
                                <p> Foster a sense of community and engagement by responding to comments, messages, and reviews promptly.</p>
                                <a href="single.html" class="read-more">Read More</a>
                            </div><!-- End .entry-content -->
                        </div><!-- End .entry-body -->
                    </article><!-- End .entry -->
                </div><!-- End .owl-carousel -->
            </div><!-- container -->

        <section id="conclusion">
            <h2>Conclusion</h2>
            <p>Enjoy your shopping experience.</p>
        </section>

        <!-- <footer>
            <p>Copyright @ 2024 TUNDA Store. All rights reserved</p>
            
        </footer> -->
    </article>
    

        <!-- <div class="more-container text-center mb-0 mt-3">
            <a href="blog.html" class="btn btn-outline-darker btn-more"><span>View more articles</span><i class="icon-long-arrow-right"></i></a>
        </div> -->

    

</body>
{% endblock page_content %}


{% block custom_js %}
{% endblock custom_js %}

DjangoEcommerce/DjangoEcommerceApp/templates/customer/cart.html
{% extends 'customer/base.html' %}
{% load static %}

{% block page_content %}
<main class="main">
    <div class="page-header text-center" style="background-image: url({% static 'assets/img/news/img13.jpg' %});">

        		<div class="container">
        			<h1 class="page-title">Shopping Cart<span>Shop</span></h1>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->
            <nav aria-label="breadcrumb" class="breadcrumb-nav">
                <div class="container">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Shopping Cart</li>
                    </ol>
                </div><!-- End .container -->
            </nav><!-- End .breadcrumb-nav -->

            <div class="page-content">
            	<div class="cart">
	                <div class="container">
	                	<div class="row">
    <div class="col-lg-9">
        <form method="post" action="{% url 'update_cart' %}">
            {% csrf_token %}
            <table class="table table-cart table-mobile">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                </thead>
				<tbody>
					{% for item in cart_items %}
					<tr>
						<td class="product-col">
							<div class="product">
								<figure class="product-media">
									{% for media in item.product_id.productmedia_set.all %}
									<a href="#">
										<img src="{{ media.media_content }}" alt="Product image">
									</a>
									{% endfor %}
								</figure>
										
								<h3 class="product-title">
									<a href="#">{{ item.product_id.product_name }}</a>
								</h3>
							</div>
						</td>
						<td class="price-col">${{ item.product_id.product_max_price }}</td>
						<td class="quantity-col">
							<div class="cart-product-quantity">
								<input type="number" class="form-control" name="quantity_{{ item.id }}" value="{{ item.quantity }}" min="1" max="10" step="1" data-decimals="0" required>
							</div><!-- End .cart-product-quantity -->
						</td>
						<td class="total-col">${{ item.total }}</td>
						<td class="remove-col"><button class="btn-remove"><i class="icon-close"></i></button></td>									
					</tr>
					{% endfor %}
				</tbody>
				
				
            </table><!-- End .table table-wishlist -->

            <div class="cart-bottom">
                <div class="cart-discount">
                    <div class="input-group">
                        <input type="text" class="form-control" name="coupon_code" placeholder="Enter coupon code">
                        <div class="input-group-append">
                            <button class="btn btn-outline-primary-2" type="submit"><i class="icon-long-arrow-right"></i></button>
                        </div><!-- .End .input-group-append -->
                    </div><!-- End .input-group -->
                </div><!-- End .cart-discount -->

                <button type="submit" class="btn btn-outline-dark-2"><span>UPDATE CART</span><i class="icon-refresh"></i></button>
            </div><!-- End .cart-bottom -->
        </form>
    </div><!-- End .col-lg-9 -->

    <aside class="col-lg-3">
        <div class="summary summary-cart">
            <h3 class="summary-title">Cart Total</h3><!-- End .summary-title -->

            <table class="table table-summary">
                <tbody>
                    <tr class="summary-subtotal">
                        <td>Subtotal:</td>
                        <td>${{ cart_subtotal }}</td>
                    </tr><!-- End .summary-subtotal -->
                    <tr class="summary-discount">
                        <td>Discount:</td>
                        <td>${{ discount_amount }}</td>
                    </tr><!-- End .summary-discount -->
                    <tr class="summary-total">
                        <td>Total:</td>
                        <td>${{ cart_total }}</td>
                    </tr><!-- End .summary-total -->
                </tbody>
            </table><!-- End .table table-summary -->

            <a href="{% url 'checkout' %}" class="btn btn-outline-primary-2 btn-order btn-block">PROCEED TO CHECKOUT</a>
        </div><!-- End .summary -->
    </aside><!-- End .col-lg-3 -->
</div><!-- End .row -->

	                </div><!-- End .container -->
                </div><!-- End .cart -->
            </div><!-- End .page-content -->
        </main><!-- End .main -->
		<script>
			document.addEventListener('DOMContentLoaded', function() {
				// Function to update the subtotal, discount, and total
				function updateSummary() {
					var subtotal = 0;
					var discount = parseFloat(document.querySelector('.summary-discount td:last-child').textContent.replace('$', ''));
					document.querySelectorAll('.cart-product-quantity input').forEach(function(input) {
						var quantity = parseInt(input.value);
						var price = parseFloat(input.getAttribute('data-price'));
						subtotal += quantity * price;
					});
					var total = subtotal - discount;
			
					document.querySelector('.summary-subtotal td:last-child').textContent = '$' + subtotal.toFixed(2);
					document.querySelector('.summary-total td:last-child').textContent = '$' + total.toFixed(2);
				}
			
				// Attach the event listener to all quantity input fields
				document.querySelectorAll('.cart-product-quantity input').forEach(function(input) {
					// Set the data-price attribute with the product's price
					input.setAttribute('data-price', input.closest('tr').querySelector('.price-col').textContent.replace('$', ''));
			
					// Update the summary on quantity change
					input.addEventListener('change', function() {
						updateTotalPrice(this);
						updateSummary();
					});
				});
			
				// Function to update the total price for an item
				function updateTotalPrice(quantityInput) {
					var quantity = parseInt(quantityInput.value);
					var price = parseFloat(quantityInput.getAttribute('data-price'));
					var total = quantity * price;
					var totalCol = quantityInput.closest('tr').querySelector('.total-col');
					totalCol.textContent = '$' + total.toFixed(2);
				}
			});
			</script>
		
{% endblock page_content %}

DjangoEcommerce/DjangoEcommerceApp/templates/customer/test.html
{% extends 'customer/base.html' %}
{% load static %}
{% block custom_css %}
{% endblock custom_css %}

{% block page_content %}

{% endblock page_content %}


{% block custom_js %}
{% endblock custom_js %}